version: '3.9'

services:
  api:
    build: ./api
    restart: always
    working_dir: /usr/src/app/api
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: go run ./cmd -b 0.0.0.0
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - 3000:3000
    restart: always

volumes:
  postgres-db:
  redis-data:
