version: '3.9'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      restart: always
    env_file:
      - ./api/.env
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    command: go run ./cmd -b 0.0.0.0
    # command: /go/bin/dlv --listen=:4000 --headless=true --log=true --accept-multiclient --api-version=2 exec /usr/src/app/main
    depends_on:
      - db
      - redis
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server
  nginx: build

volumes:
  postgres-db:
  redis-data:
