version: '3.9'

services:
  api:
    build: ./api
    restart: always
    working_dir: /usr/src/app/api
    env_file:
      - .env
    # ports:
    #   - "3000:3000"
    #   - "4000:4000"
    volumes:
      - .:/usr/src/app
    command: go run ./cmd -b 0.0.0.0

    # command: /go/bin/dlv --listen=:4000 --headless=true --log=true --accept-multiclient --api-version=2 exec /usr/src/app/main
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - 3000:3000
    restart: always

volumes:
  postgres-db:
  redis-data:
